### ISSUE TITLE
Can this be tweak to use from the code running on node-telegram-bot-api?

### ISSUE THREAD

**Issue by ErKiran** [gianlucaparadise/telegraf-calendar-telegram#8]
I have programmed demo bot using node-telegram-bot-API and now I am planning to integrate my bot with the calendar. Can this be tweaked so that it can be run from the bot powered by node-telegram-bot-api instead of telegraf?

**Comment by gianlucaparadise** [comment]
I really don't think so, because the library is very tied to the Telegraf framework. But most of the job is done by the [CalendarHelper](https://github.com/gianlucaparadise/telegraf-calendar-telegram/blob/master/calendar-helper/index.js) class.
The only Telegraf code you can see there is the one used to build the HTML buttons. I don't know `node-telegram-bot-API`, but in my opinion it wouldn't be big refactor.

Let me know if you need help in understanding my code.
